import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import { Background } from "@/shared/components/shared";
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "CrackChecker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.className}>
      <body className="text-figtree h-screen overflow-x-hidden selection:bg-red-500 ">
        <Background />
        <main>{children}</main>
      </body>
    </html>
  );
}
