import type { Metadata } from "next";
import './globals.css';

import scandia from 'next/font/local';

import { SiteApi } from '@/services/siteApi/apiClient';
import { Footer } from '@/shared/components';
import { Header } from '@/shared/components/header';
import { Providers } from '@/shared/components/providers';
import { Background } from '@/shared/components/shared';
import { Toaster } from '@/shared/components/ui/shadcn';

const Scandia = scandia({
  src: [
    {
      path: "../public/fonts/Scandia-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Scandia-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Scandia-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "CrackChecker - Crack Status, Game release calendar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const payload = await SiteApi.users.getJWTPayloadFromCookies();
  const userData = payload
    ? { id: payload.id, name: payload.name, email: payload.email }
    : null;

  return (
    <html lang="en" className={Scandia.className}>
      <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      </head>
      <body className="flex flex-col overflow-x-hidden selection:bg-red-500 text-white">
        <Providers userData={userData}>
          <Background />
          <Header />
          <main>{children}</main>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
