import { Metadata } from "next";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "CrackChecker - Placeholder",
  description: "Generated by create next app",
};

export default function GameLayout({ children }: PropsWithChildren) {
  return <div>{children}</div>;
}
